apiVersion: config.istio.io/v1beta1
kind: DestinationPolicy
metadata:
  name: httpbin-least-conn-cb
spec:
  destination:
    name: httpbin
    labels:
      version: v1
  loadBalancing:
    name: LEAST_CONN
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxPendingRequests: 1
      sleepWindow: 3m
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100
      httpConsecutiveErrors: 1
      httpMaxRequestsPerConnection: 1
